services:
  # Frontend service (development)
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001
      - DOCKER=true
    depends_on:
      - backend-dev
    networks:
      - app-network
    command: npm run dev

  # Backend service (development)
  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - JWT_SECRET=dev-secret-key
      - JWT_EXPIRES_IN=7d
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=1000
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost:4173
      - DB_HOST=mysql-dev
      - DB_PORT=3306
      - DB_USER=social_content_user
      - DB_PASSWORD=social_content_password
      - DB_NAME=social_content_ai
    depends_on:
      mysql-dev:
        condition: service_healthy
    networks:
      - app-network
    command: npm run dev

  # MySQL Database (development)
  mysql-dev:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: social_content_ai
      MYSQL_USER: social_content_user
      MYSQL_PASSWORD: social_content_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "social_content_user", "-p social_content_password"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  app-network:
    driver: bridge

volumes:
  mysql_dev_data:
